<a href="https://colab.research.google.com/github/Arun-Varghese2312/Sentiment-Analysis/blob/main/Module_5_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sentiment Analysis

Import Libraries

In [10]:
# Basic libraries
import pandas as pd
import numpy as np
import re
import string

# NLP libraries
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, f1_score

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

Load Dataset

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
# Load dataset
file_path = "/content/drive/My Drive/Entri Assignments/Module 5 Sentiment Analysis/nlp_dataset.csv"

df = pd.read_csv(file_path)

# Display first 5 rows
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

Check Dataset

In [13]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5937 entries, 0 to 5936
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Comment  5937 non-null   object
 1   Emotion  5937 non-null   object
dtypes: object(2)
memory usage: 92.9+ KB

In [19]:
df.columns

Index(['Comment', 'Emotion'], dtype='object')

In [14]:
# Check missing values
df.isnull().sum()

Comment    0
Emotion    0
dtype: int64

In [15]:
# View class distribution
df['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [16]:
df.columns

Index(['Comment', 'Emotion'], dtype='object')

TEXT PREPROCESSING

In [22]:
stop_words = set(stopwords.words('english'))

def preprocess_text(text):

    text = text.lower()  # lowercase

    text = re.sub(f"[{string.punctuation}]", "", text)  # remove punctuation

    text = re.sub(r'\d+', '', text)  # remove numbers

    # 🔥 FIXED: replaced word_tokenize with split()
    tokens = text.split()

    tokens = [word for word in tokens if word not in stop_words]

    return " ".join(tokens)

Apply Preprocessing

In [23]:
df['clean_text'] = df['Comment'].apply(preprocess_text)

In [24]:
df[['Comment', 'clean_text']].head()

,Comment,clean_text
0,i seriously hate one subject to death but now ...,seriously hate one subject death feel reluctan...
1,im so full of life i feel appalled,im full life feel appalled
2,i sit here to write i start to dig out my feel...,sit write start dig feelings think afraid acce...
3,ive been really angry with r and i feel like a...,ive really angry r feel like idiot trusting fi...
4,i feel suspicious if there is no one outside l...,feel suspicious one outside like rapture happe...

FEATURE EXTRACTION

In [25]:
X = df['clean_text']
y = df['Emotion']

vectorizer = TfidfVectorizer(max_features=5000)

X_vectorized = vectorizer.fit_transform(X)

TRAIN TEST SPLIT

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

NAIVE BAYES MODEL

In [27]:
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

MultinomialNB()

NAIVE BAYES PREDICTION

In [28]:
nb_pred = nb_model.predict(X_test)

NAIVE BAYES EVALUATION

In [29]:
nb_acc = accuracy_score(y_test, nb_pred)
nb_f1 = f1_score(y_test, nb_pred, average='weighted')

print("Naive Bayes Accuracy:", nb_acc)
print("Naive Bayes F1:", nb_f1)

print(classification_report(y_test, nb_pred))

Naive Bayes Accuracy: 0.9099326599326599
Naive Bayes F1: 0.909789362255079
              precision    recall  f1-score   support

       anger       0.88      0.95      0.91       392
        fear       0.92      0.92      0.92       416
         joy       0.95      0.86      0.90       380

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188

SVM MODEL

In [30]:
svm_model = LinearSVC()
svm_model.fit(X_train, y_train)

LinearSVC()

SVM PREDICTION

In [31]:
svm_pred = svm_model.predict(X_test)

SVM EVALUATION

In [32]:
svm_acc = accuracy_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred, average='weighted')

print("SVM Accuracy:", svm_acc)
print("SVM F1:", svm_f1)

print(classification_report(y_test, svm_pred))

SVM Accuracy: 0.952020202020202
SVM F1: 0.9519894469368267
              precision    recall  f1-score   support

       anger       0.94      0.96      0.95       392
        fear       0.97      0.93      0.95       416
         joy       0.95      0.97      0.96       380

    accuracy                           0.95      1188
   macro avg       0.95      0.95      0.95      1188
weighted avg       0.95      0.95      0.95      1188

MODEL COMPARISON

In [33]:
comparison = pd.DataFrame({
    "Model": ["Naive Bayes", "SVM"],
    "Accuracy": [nb_acc, svm_acc],
    "F1 Score": [nb_f1, svm_f1]
})

comparison

         Model  Accuracy  F1 Score
0  Naive Bayes  0.909933  0.909789
1          SVM  0.952020  0.951989